let express=require("express")
const postReq = require("../controllers/addProducts")
const getReq =require("../controllers/getReq")
const deletReq = require("../controllers/deleteRq")
const putReq = require("../controllers/putREq")
const patchReq = require("../controllers/patchReq")
const register = require("../controllers/register")
const login = require("../controllers/login")
const authentication = require("../middlewares/authentication")
const addProducts = require("../controllers/addProducts")
const {checking_Admin_costomer, checking_Admin_costomer_user, checking_admin} = require("../middlewares/checkingrRoles")
// const Auth = require("../controllers/Auth")
let router=express.Router()
router.post("/add",checking_Admin_costomer(["admin","costomer"]), addProducts)
router.get("/getdata",checking_Admin_costomer_user(["admin","costomer","user"]), getReq)//
router.delete("/delete/:id",checking_admin(["admin"]),deletReq)
router.put("/update/:id",checking_admin(["admin"]), putReq)
router.patch("/patch/:id",checking_admin(["admin"]),patchReq)
router.post("/register", register)
router.post("/login",login)
module.exports=router